#!/bin/sh
set -eu

repository="mrshyi/java_oci_manager"
branch="main"
image="ghcr.io/mrshyi/java_oci_manager:latest"
deploy_dir="${DEPLOY_DIR:-java_oci_manager}"
platform_file="compose.platform.yaml"
archive_url="https://github.com/${repository}/archive/refs/heads/${branch}.tar.gz"

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

for command in docker curl tar sed; do
  command -v "${command}" >/dev/null 2>&1 || fail "${command} is required"
done

docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required"
docker info >/dev/null 2>&1 || fail "Docker is not running or the current user cannot access it"

if [ -e "${deploy_dir}" ]; then
  [ -d "${deploy_dir}" ] || fail "${deploy_dir} exists and is not a directory"
  [ -z "$(ls -A "${deploy_dir}")" ] || fail "${deploy_dir} already exists and is not empty"
else
  mkdir -p "${deploy_dir}"
fi


printf 'Downloading deployment files...\n'
curl --fail --silent --show-error --location "${archive_url}" \
  | tar --extract --gzip --directory "${deploy_dir}" --strip-components=1
platform_result="$(RBOT_PLATFORM="${RBOT_PLATFORM:-auto}" sh "${deploy_dir}/scripts/select-platform.sh")"
selected_platform="$(printf '%s\n' "${platform_result}" | sed -n 's/^platform=//p')"
platform_reason="$(printf '%s\n' "${platform_result}" | sed -n 's/^reason=//p')"
machine="$(printf '%s\n' "${platform_result}" | sed -n 's/^machine=//p')"


cp "${deploy_dir}/.env.example" "${deploy_dir}/.env"
sed -i.bak "s|^RBOT_IMAGE=.*|RBOT_IMAGE=${image}|" "${deploy_dir}/.env"
rm -f "${deploy_dir}/.env.bak"
mkdir -p "${deploy_dir}/config" "${deploy_dir}/secrets"
cat > "${deploy_dir}/${platform_file}" <<EOF
services:
  rbot:
    platform: ${selected_platform}
EOF
{
  printf '\n# Generated by scripts/install.sh; keeps platform selection on upgrades.\n'
  printf 'RBOT_PLATFORM=%s\n' "${selected_platform}"
  printf 'COMPOSE_FILE=compose.yaml:%s\n' "${platform_file}"
} >> "${deploy_dir}/.env"


printf 'Selected %s (%s).\n' "${selected_platform}" "${platform_reason}"
printf 'Pulling %s...\n' "${image}"
docker pull --platform "${selected_platform}" "${image}"

if ! docker run --rm \
  --platform "${selected_platform}" \
  --entrypoint /bin/true \
  "${image}"; then
  if [ "${machine}" = aarch64 ] || [ "${machine}" = arm64 ]; then
    fail "cannot run ${selected_platform} on this ARM64 host. Install x86_64 binfmt/QEMU (Debian/Ubuntu: apt-get update && apt-get install -y qemu-user-static binfmt-support), then run: cd ${deploy_dir} && docker compose up -d --no-build"
  fi
  fail "cannot run ${selected_platform} containers on this host"
fi

printf 'Starting the service...\n'
(
  cd "${deploy_dir}"
  docker compose up -d --no-build
  docker compose ps
)


printf '\nDeployment completed.\n'
printf 'Open http://SERVER_IP:9527 (or http://127.0.0.1:9527 on the host).\n'
printf 'HTTP is intended for quick testing; configure a trusted reverse proxy before production use.\n'
printf 'The default bind address is public; restrict the firewall or set RBOT_BIND_ADDRESS=127.0.0.1 when testing is finished.\n'
printf 'Deployment directory: %s\n' "$(cd "${deploy_dir}" && pwd)"
printf 'Selected container platform: %s (saved in %s).\n' "${selected_platform}" "${platform_file}"
printf 'View logs: cd %s && docker compose logs --tail=200 -f rbot\n' "${deploy_dir}"
